# Generated by Django 6.0.5 on 2026-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
